/camera_node:
  ros__parameters:
    general_camera_path: "/dev/v4l/by-path/platform-5200000.usb-usb-0:1:1.0-video-index0"
    field_camera_path: "/dev/v4l/by-path/pci-0000:00:14.0-usb-0:9:1.0-video-index0"
    publish_timer: 0.03 # 10 fps
    frame_width: 640
    frame_height: 480

/flask_node:
  ros__parameters:
    port: 8080
    host: "0.0.0.0"
    joystick_offset: 0.01 # meters

/urx_node:
  ros__parameters:
    ip: "192.168.1.2"
    popup_message: "Dashboard message"
    status_publish_rate: 0.5 # second
    gripper_start_pose: 0 # 0 - 255
    gripper_step: 10 # 0 - 255


/robot_control:
  ros__parameters:
    gripper:
      max: 100
      min: 0
    movel: # meters
      x_min: -0.4
      x_max: 0.1

      y_max: 0.3
      y_min: -0.3

      z_min: 0.0
      z_max: 0.35

      velocity: 0.15
      acceleration: 0.15


# -0.25 0.25
# -0.150 -0.5
# 0.01 0.2
