/camera_node:
  ros__parameters:
    general_camera_path: "/dev/v4l/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1:1.0-video-index0"
    field_camera_path: "/dev/v4l/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3:1.0-video-index0"
    publish_timer: 0.03 # 10 fps